engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: true
    exclude_paths:
    - src/locales
  eslint:
    enabled: true
    config:
      # config: .eslintrc.yml
      channel: eslint-4
      extensions:
      - .js
      - .vue
  fixme:
    enabled: true
  # Waiting on https://github.com/nodesecurity/nsp/pull/142 to support yarn.lock
  nodesecurity:
    enabled: false
  markdownlint:
    enabled: true
    checks:
      MD024:
        enabled: false
      MD029:
        enabled: false
      MD033:
        enabled: false
  scss-lint:
    enabled: true
    checks:
      NameFormat:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.vue"
  - "**.sass"
  - "**.md"
exclude_paths:
- .vscode
- static
- build
- config
- src/locales
